version: "3.0"

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    volumes:
        - cockroach-db-data:/var/lib/cockroach/data
    command: start-single-node --insecure
    ports:
        - "26257:26257"
        - "8080:8080"
    networks:
        - cockroachdb_net

volumes:
  cockroach-db-data:

networks:
  cockroachdb_net:
